
import { Course } from './types';

export const courses: Course[] = [
  {
    id: 1,
    title: 'Advanced React and TypeScript',
    instructor: 'Jane Doe',
    description: 'Master modern React patterns with TypeScript for scalable applications.',
    longDescription: 'This course dives deep into advanced React concepts, including hooks, context API, performance optimization, and state management. You will also learn how to leverage TypeScript to build type-safe, maintainable, and robust React applications. Topics include generics, advanced types, and integrating with popular libraries.',
    rating: 4.8,
    totalRatings: 1250,
    duration: '12h 30m',
    level: 'Advanced',
    imageUrl: 'https://picsum.photos/seed/react/600/400',
  },
  {
    id: 2,
    title: 'UI/UX Design Fundamentals',
    instructor: 'John Smith',
    description: 'Learn the principles of user-centric design and create intuitive interfaces.',
    longDescription: 'Explore the fundamentals of UI/UX design, from user research and wireframing to prototyping and usability testing. This course covers design principles, color theory, typography, and the tools you need to create beautiful and effective user experiences. You will work on a portfolio project to apply your skills.',
    rating: 4.9,
    totalRatings: 3400,
    duration: '8h 15m',
    level: 'Beginner',
    imageUrl: 'https://picsum.photos/seed/uiux/600/400',
  },
  {
    id: 3,
    title: 'Mastering Python for Data Science',
    instructor: 'Emily White',
    description: 'Unlock the power of Python for data analysis, visualization, and machine learning.',
    longDescription: 'This comprehensive course covers the essential Python libraries for data science, including NumPy, Pandas, Matplotlib, and Scikit-learn. You will learn data manipulation, exploratory data analysis, and how to build and evaluate machine learning models. Real-world datasets will be used for hands-on practice.',
    rating: 4.7,
    totalRatings: 5600,
    duration: '20h 45m',
    level: 'Intermediate',
    imageUrl: 'https://picsum.photos/seed/python/600/400',
  },
  {
    id: 4,
    title: 'Introduction to Cloud Computing',
    instructor: 'Michael Brown',
    description: 'Understand the core concepts of cloud services with AWS, Azure, and GCP.',
    longDescription: 'Get a solid foundation in cloud computing. This course explains concepts like IaaS, PaaS, and SaaS, and provides an overview of the major cloud providers: Amazon Web Services, Microsoft Azure, and Google Cloud Platform. You will learn about virtual machines, storage, databases, and serverless computing.',
    rating: 4.6,
    totalRatings: 2100,
    duration: '6h',
    level: 'Beginner',
    imageUrl: 'https://picsum.photos/seed/cloud/600/400',
  },
  {
    id: 5,
    title: 'Creative Digital Marketing',
    instructor: 'Sarah Green',
    description: 'Build effective marketing strategies for the modern digital landscape.',
    longDescription: 'Learn to navigate the world of digital marketing. This course covers SEO, content marketing, social media strategy, email marketing, and PPC advertising. You will develop skills to create, manage, and analyze marketing campaigns that drive growth and engagement.',
    rating: 4.8,
    totalRatings: 1850,
    duration: '10h',
    level: 'Intermediate',
    imageUrl: 'https://picsum.photos/seed/marketing/600/400',
  },
  {
    id: 6,
    title: 'Cybersecurity Essentials',
    instructor: 'David Wilson',
    description: 'Protect systems and data from cyber threats with essential security knowledge.',
    longDescription: 'This course provides a foundational understanding of cybersecurity principles. Topics include threat actors, network security, cryptography, access management, and incident response. Learn how to identify vulnerabilities and implement security best practices to protect digital assets.',
    rating: 4.9,
    totalRatings: 4200,
    duration: '15h 20m',
    level: 'Beginner',
    imageUrl: 'https://picsum.photos/seed/security/600/400',
  },
];
